### ISSUE TITLE
models.py not available to use in models_bridge.py

### ISSUE THREAD

**Issue by chandagrover** [hywang66/mmist#2]
Hi Team, 

Thank you for your great work and for making the code public.

There is no models python file available in your repository. I am getting the below error while reproducing the code in model_bridge.py:
ModuleNotFoundError: No module named 'models'

Could you please provide models.py file?

Thanks,
Chanda Grover.

**Comment by hywang66** [comment]
Did you also clone the AdaAttN repo and correctly set the `adaattn_path` argument? The `models` is actually a module in the AdaAttN repo: https://github.com/hywang66/AdaAttN/tree/4fcfc75cf85193b1aac49067653b7248a255f7e9/models

Please make sure that you clone this repo recursively so that the dependencies (adaattn and stylegan3) are also cloned.

**Comment by chandagrover** [comment]
yes. I missed that. thanks.
